Set `isPublic` state for database and collection
oulib-datacatalog/cybercommons pull request #21
Opened 2023-04-05 22:17 UTC by Rithsek99

2023-04-05 22:29 UTC, Rithsek99 commented
I tried to do two PRs but it seem to combine them together.

2023-04-24 22:11 UTC, tdpearson requested changes
Update your PR with my requested changes. Let me know if you have any questions or if something is not clear.

2023-04-24 22:11 UTC, tdpearson commented on Dockerfile
Keep the original without the reload. Reload is helpful in local dev but should not be used in prod.

2023-04-24 22:11 UTC, tdpearson commented on catalog/management/catalog_perms.py
> +            if database not in config.CATALOG_EXCLUDE:
Update this to check if database is in config.CATALOG_INCLUDE.

2023-04-24 22:11 UTC, tdpearson commented on catalog/management/catalog_perms.py
move this file to `catalog/management/commands/catalog_perms.py`

2023-04-24 22:11 UTC, tdpearson commented on dc_config/cybercom_config.env
Set DEBUG back to False

2023-04-24 22:11 UTC, tdpearson commented on dc_config/images/docker-compose-init.yml
Remove from PR

2023-04-24 22:11 UTC, tdpearson commented on dc_config/images/sqlite3/Dockerfile
Remove from PR

2023-04-24 22:11 UTC, tdpearson commented on dc_config/images/sqlite3/create_db.sh
Remove from PR

2023-04-24 22:11 UTC, tdpearson commented on dc_config/images/sqlite3/django.sql
Remove from PR

2023-04-24 22:11 UTC, tdpearson commented on dc_config/images/sqlite3/dump_db.sh
Remove from PR

2023-04-24 22:11 UTC, tdpearson commented on docker-compose.yml
Remove sqlite3 volume

2023-04-24 22:11 UTC, tdpearson commented on db.sqlite3
Reset this file from the main branch from the oulib-datacatalog repo and rerun migrations after reset.

2023-04-24 22:11 UTC, tdpearson commented on data_store/views.py
This looks good and we can leave this as is. I will look into the changes to support access to private items for non-admin users if the need arises.

2023-04-24 22:11 UTC, tdpearson commented on catalog/models.py
Subclassing the DatabasePermission and CollectionPermission from data_store causes PKs from the data_store_*permission tables to be referenced in the catalog_catalog_*permission tables instead of creating unique entries. Take a look at Django's documentation that can help explain what is going on and an alternative implementation: https://docs.djangoproject.com/en/4.2/topics/db/models/#model-inheritance

2023-05-11 19:24 UTC, tdpearson approved these changes

2023-05-11 19:28 UTC, tdpearson commented
Great work, Rithsek. To document what is left to do:

- Run migrations on db.sqlite3 files to incorporate model changes
- screenshots of admin permission for documentation to show or hide databases and collections
- Extend permissions to allow those that have "SAFE_METHODs" permission to view hidden database or collection

2023-05-11 19:30 UTC, merged